version: '3.8'
name: 'medopd'
volumes:
  medopd_redis_data:
  medopd_postgres_data:
services:
  # redis:
  #   image: redis:7.2
  #   restart: 'no'
  #   container_name: medopd_redis
  #   command: --loglevel notice
  #   volumes:
  #     - medopd_redis_data:/data
  #   ports:
  #     - 6379:6379
  postgres:
    image: postgres:14-bullseye
    container_name: medopd_postgres
    command: -c log_statement=all
    restart: 'no'
    # depends_on:
    #   - redis
    volumes:
      - medopd_postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - PGPASSWORD=postgres
      - POSTGRES_DB=dev
    ports:
      - 5432:5432
  # pgadmin:
  #   image: dpage/pgadmin4
  #   restart: "no"
  #   depends_on:
  #   - postgres
  #   ports:
  #   - 5050:80
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: pgadmin@example.com
  #     PGADMIN_DEFAULT_PASSWORD: admin
